input_file_path: "./inputfile_bacillaria.dat"
output_directory: "./"
nb_blobs: 2
nb_rods: 3
dt: 0.0025
nb_step: 20
nb_episodes: 10
learning_rate: 0.1
discount_factor: 0.6
lookahead_steps: 1
reward_method: "FORWARD_PROGRESS"
reward_angle: 90.0