input_file_path: "./inputfile_bacillaria.dat"
output_directory: "./"
nb_blobs: 10
nb_rods: 9
dt: 0.0025
nb_step: 200
nb_episodes: 2000
learning_rate: 0.1
discount_factor: 0.6
reward_method: "FORWARD_PROGRESS"
reward_angle: 90.0